version: 2.1
description: |
    Maven orb to be used in all archmix circleci builds
display:
    source_url: https://github.com/archmix/infra-maven
commands:
    prepare_maven_environment:
        description: Imports GPG key and download settings.xml file
        steps:
            - run:
                command: |
                    curl https://raw.githubusercontent.com/archmix/infra-maven/master/settings.xml >> settings.xml
                name: Importing Settings from Github
            - run:
                command: |
                    echo -e "$MAVEN_GPG_KEY" | gpg --import
                name: Importing GPG Key
jobs:
    build:
        docker:
            - image: cimg/openjdk:11.0.22
        environment:
            MAVEN_OPTS: -Xmx3200m
        steps:
            - checkout
            - prepare_maven_environment
            - run: mvn -s settings.xml clean deploy
        working_directory: ~/repo
    build_machine:
        environment:
            MAVEN_OPTS: -Xmx3200m
        machine:
            image: ubuntu-1604:201903-01
        steps:
            - checkout
            - prepare_maven_environment
            - run: mvn -s settings.xml clean deploy
        working_directory: ~/repo
    release:
        docker:
            - image: cimg/openjdk:11.0.22
        steps:
            - add_ssh_keys
            - checkout
            - prepare_maven_environment
            - run: git config user.email "ci@archmix.org"
            - run: git config user.name "Circle CI"
            - run: mvn -DskipTests -P release -B -s settings.xml release:clean release:prepare release:perform -DignoreSnapshots=true
        working_directory: ~/repo

