version: 2.1
setup: true

orbs:
  orb-tools: circleci/orb-tools@12.3.1
  shellcheck: circleci/shellcheck@3.2

branch-filter: &branch-filter
  branches:
    ignore: 
      - dev
      - master

workflows:
  test-or-publish:
    jobs:
      - orb-tools/continue:
          name: test-orb
          orb_name: maven
          pipeline_number: <<pipeline.number>>
          vcs_type: <<pipeline.project.type>>
          config_path: .circleci/test-orb.yml
          filters: *branch-filter

      - orb-tools/continue:
          name: publish-orb
          orb_name: maven
          pipeline_number: <<pipeline.number>>
          vcs_type: <<pipeline.project.type>>
          config_path: .circleci/publish-orb.yml
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
