version: 2.1
setup: true

orbs:
  orb-tools: circleci/orb-tools@12.3.1
  shellcheck: circleci/shellcheck@3.2

dev-filters: &dev-filters
  branches:
    ignore: main

workflows:
  lint:
    jobs:
      - orb-tools/lint:
          name: lint
          filters: *dev-filters
      - orb-tools/pack:
          name: pack
          filters: *dev-filters
      - shellcheck/check:
          name: check
          filters: *dev-filters
      - orb-tools/continue:
          name: continue
          orb_name: maven
          pipeline_number: <<pipeline.number>>
          vcs_type: <<pipeline.project.type>>
          requires:
            - lint
            - pack
            - check
          filters: *dev-filters
  release:
    jobs:
      - orb-tools/publish:
          context: shared-circleci-token
          orb_name: archmix/maven
          vcs_type: <<pipeline.project.type>>
          pub_type: production
          circleci_token: CIRCLECI_API_TOKEN
          enable_pr_comment: false
          filters:
            branches:
              only: master
