version: 2.1
setup: true

orbs:
  orb-tools: circleci/orb-tools@12
  shellcheck: circleci/shellcheck@3.2

workflows:
  release:
    jobs:
      - orb-tools/lint:
          name: lint
      - orb-tools/pack:
          name: pack
      - shellcheck/check:
          name: check
     
      - orb-tools/continue:
          name: continue
          orb_name: maven
          pipeline_number: <<pipeline.number>>
          vcs_type: <<pipeline.project.type>>
          requires:
            - lint
            - pack
            - check
      
      - orb-tools/publish:
          context: shared-circleci-token
          orb_name: archmix/maven
          vcs_type: <<pipeline.project.type>>
          pub_type: production
          circleci_token: CIRCLECI_API_TOKEN
          enable_pr_comment: false
          requires:
            - continue
          filters:
            branches:
              only: master
