version: 2.1
setup: true

orbs:
  orb-tools: circleci/orb-tools@12.3.1
  shellcheck: circleci/shellcheck@3.2

branch-filter: &branch-filter
  branches:
    ignore: 
      - dev
      - master

branch-or-tag-filter: &branch-or-tag-filter
  branches:
    ignore: master
  tags:
    only: /^v.*/

workflows:
  test-or-publish:
    jobs:
      - orb-tools/lint:
          name: lint
          filters: *branch-or-tag-filter
      - orb-tools/pack:
          name: pack
          filters: *branch-or-tag-filter
          requires: 
            - lint
      - shellcheck/check:
          name: check
          filters: *branch-filter
          requires: 
            - pack

      - orb-tools/continue:
          name: test-orb
          orb_name: maven
          pipeline_number: <<pipeline.number>>
          vcs_type: <<pipeline.project.type>>
          config_path: .circleci/test-orb.yml
          filters: *branch-filter
          requires: 
            - pack

      - orb-tools/publish:
          name: publish
          context: Archmix
          orb_name: archmix/maven
          vcs_type: <<pipeline.project.type>>
          pub_type: production
          circleci_token: CIRCLECI_API_TOKEN
          enable_pr_comment: false
          requires:
            - pack
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          
