description: Imports GPG key and download settings.xml file

steps:
  - run:
      name: Importing Settings from Github
      command: |
        curl https://raw.githubusercontent.com/archmix/infra-maven/master/settings.xml >> settings.xml
  - run:
      name: Importing GPG Key
      command: |
        echo -e "$MAVEN_GPG_KEY" | gpg --import
