docker:
  - image: circleci/openjdk:8-jdk

working_directory: ~/repo

environment:
  MAVEN_OPTS: -Xmx3200m

steps:
  - checkout
  - prepare_maven_environment
  - run: mvn -s settings.xml clean deploy
